### ISSUE TITLE
Completion does not cover prefixed environemnts

### ISSUE THREAD

**Issue by johannes-mueller** [conda-incubator/conda-zsh-completion#54] opened 2024-03-04 07:33 UTC
I often have conda environments in local directories like `.venv`, `.venv-broken`, `.venv-3.12`. Unfortunately `conda activate <TAB>` does not complete to them.

**Comment by esc** [comment] 2024-03-04 13:43
@johannes-mueller I think this may be a quasi duplicate of https://github.com/conda-incubator/conda-zsh-completion/issues/51

I assume that essentially you need some kind of configuration variable that allows you to add additional paths or patterns (globs?) of paths to the paths that are searched by the completion widget to complete environments?

**Closed** 2024-03-05 14:59 UTC
